[package]
name = "wows-scripts-deobfuscator"
version = "0.1.0"
authors = ["Lander Brandt <landerbrandt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5"
structopt = "0.3"
memmap = "0.7"
byteorder = "1.3"
py-marshal = "0.3.3"
python_object = "0.1.0"